// NECESITAMOS

// 1. LAS CARTAS
// 2. EL REVERSO DE LAS CARTAS
// 3. QUE SE GIREN LAS CARTAS AL HACER CLICK
// 4. QUE SI DOS CARTAS TIENEN LA MISMA CARA SE QUEDEN GIRADAS Y LO TENGA EN CUENTA
// 5. SI SE CONSIGUEN GIRAR TODAS GANAS
// 6. SI PASAN 60 SEGUNDOS Y NO LO HAS CONSEGUIDO PIERDES


// 1

